use project::AssetMeta;
use std::path::Path;

/// Walks `content_dir` for `.meta` sidecar files and generates Rust source code
/// declaring a `pub const` for each asset, named after its filename.
///
/// The returned string is valid Rust — write it to `OUT_DIR/assets.rs` from a
/// `build.rs` and include it with `include!(concat!(env!("OUT_DIR"), "/assets.rs"))`.
pub fn generate_asset_constants(content_dir: &Path) -> String {
    let mut consts: Vec<(String, String)> = Vec::new();
    collect_meta(content_dir, &mut consts);

    // Sort for stable output — avoids spurious diffs when cargo reruns.
    consts.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from("// AUTO-GENERATED by build.rs — do not edit manually.\n");
    out.push_str("// Re-run `cargo build` after adding or renaming assets.\n\n");

    for (name, guid) in &consts {
        out.push_str(&format!(
            "pub const {}: Guid = guid!(\"{}\");\n",
            name, guid
        ));
    }

    out
}

fn collect_meta(dir: &Path, consts: &mut Vec<(String, String)>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            collect_meta(&path, consts);
        } else if path.extension().and_then(|e| e.to_str()) == Some("meta") {
            let Ok(meta) = AssetMeta::load(&path) else {
                continue;
            };

            // Strip `.meta` → the asset filename, e.g. `cube.obj.meta` → `cube.obj`
            let file_name = match path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.trim_end_matches(".meta"),
                None => continue,
            };

            consts.push((to_const_name(file_name), meta.guid.to_string()));
        }
    }
}

/// Converts an asset filename to a SCREAMING_SNAKE_CASE Rust identifier.
///
/// `floor.obj` → `FLOOR_OBJ`, `brick.emat` → `BRICK_EMAT`
fn to_const_name(filename: &str) -> String {
    filename
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_uppercase()
}
